spring.application.name=postService

server.servlet.context-path=/api/v1/posts
server.port = 9010

spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
