spring.application.name=connections-service

server.port = 9030
server.servlet.context-path=/connections

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=Mayur@2000
spring.data.neo4j.database=linkedin

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
